version: '3.8'

services:
  prod_db:
    container_name: postgresql_db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  test_db:
    container_name: postgresql_test_db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "6000:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - prod_db


volumes:
  postgres_prod_data:
  postgres_test_data:
