name: coiled_steel_api_workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.1.2 ruff==0.11.0 mypy==1.15.0 pycodestyle==2.12.1 pyflakes==3.2.0 mccabe==0.7.0

      - name: Run flake8
        run: |
          flake8 src
          flake8 tests
      - name: Run ruff
        run: |
          ruff check src
          ruff check tests
      - name: Run mypy
        run: mypy src

  tests:
    runs-on: ubuntu-latest
    name: Run tests with pytest
    needs: lint

    env:
      TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
      TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
      TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
      TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}

    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
          TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
        ports:
          - 6000:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest -v
