name: coiled_steel_api_workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.1.2 ruff==0.11.0 mypy==1.15.0 pycodestyle==2.12.1 pyflakes==3.2.0 mccabe==0.7.0

      - name: Run flake8
        run: |
          flake8 src
          flake8 tests
      - name: Run ruff
        run: |
          ruff check src
          ruff check tests
      - name: Run mypy
        run: mypy src

  tests:
    runs-on: ubuntu-latest
    name: Run tests with pytest
    needs: lint

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 5432
      TEST_DB_NAME: test_postgres
      TEST_POSTGRES_USER: test_postgres_user
      TEST_POSTGRES_PASSWORD: test_postgres_password

    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_DB: test_postgres
          POSTGRES_USER: test_postgres_user
          POSTGRES_PASSWORD: test_postgres_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest -v
